// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prova_dev_API.Data;

namespace prova_dev_API.Migrations
{
    [DbContext(typeof(DataContent))]
    partial class DataContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("prova_dev_API.Models.cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("celular")
                        .HasColumnType("TEXT");

                    b.Property<int>("cpf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dtnasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("profissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("renda")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("nome");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            celular = "jfvnsjk",
                            cpf = 123456,
                            dtnasc = "gsdjfn",
                            email = "email",
                            nome = "nome",
                            profissao = "jfjsn",
                            renda = "huti"
                        },
                        new
                        {
                            Id = 2,
                            celular = "jfvnsjk",
                            cpf = 123456,
                            dtnasc = "gsdjfn",
                            email = "email",
                            nome = "nome",
                            profissao = "jfjsn",
                            renda = "huti"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
